### ISSUE TITLE
Including own NEST neuron models in the tvb-multiscale docker container: NEST version?

### ISSUE THREAD

**Issue by Ninontwik** [the-virtual-brain/tvb-multiscale#43]
Dear developers,

I have a question concerning the use of NEST in the tvb-multiscale docker container. Since the NEST support platforms could not help me, I am hoping this is the right place to ask the question. If not, please let me know. 

To include a spiking neuronal network model of the thalamus within a whole-brain model, built with tvb, I am using the tvb-multiscale docker container in Vscode on my windows PC. I am using a python 3 interpreter. So far, this has worked perfectly. However, to make a more realistic model of the thalamus, I need to install a custom version of a NEST neuron model (which is able to better simulate the behavior of thalamic neurons). To try if installing extension modules at all in this setup is possible, I've followed these steps: https://nest-extension-module.readthedocs.io/en/latest/extension_modules.html to install this example nest-extension-module: https://github.com/nest/nest-extension-module . 

Using Cmake like this in the terminal in the container works perfectly well. Using:
`(neurosci) docker@84fabd16af99:~/mmb$ cmake -Dwith-nest=/home/docker/env/neurosci/nest_build/bin/nest-config ../nest-extension-module-master`
I get the message:
```
You can now build and install 'mymodule' using
  make
  make install

The library file libmymodule.so will be installed to
  /home/docker/env/neurosci/nest_build/lib/nest/
Help files will be installed to
  /home/docker/env/neurosci/nest_build/share/doc/nest

The module can be loaded into NEST using
  nest.Install('mymodule')  (in PyNEST)
  (mymodule) Install        (in SLI)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/docker/mmb
```
However, when I try to "make", I get a long list of errors of which the first one is:
```
In file included from /home/docker/nest-extension-module-master/src/mymodule.cpp:30:
/home/docker/nest-extension-module-master/src/pif_psc_alpha.h:92:1: error: expected class-name before ‘{’ token
 {
 ^
/home/docker/nest-extension-module-master/src/pif_psc_alpha.h:115:21: error: type ‘nest::Node’ is not a base type for type ‘mynest::pif_psc_alpha’
   using nest::Node::handle;
```

According to a NEST developer, the most probable reason is that there is an old NEST version installed in the image (master@1e0ce51, dated Oct 12, 2020). If so, would it be possible for your to update the version of NEST in the container? 

If this is not the problem, do you know if it is possible to install self-defined NEST models in the tvb-multiscale container and how? 

I hope the problem is clear and this is the right place to ask. Thank you in advance and have a nice day!

Kind regards,
Nina

**Comment by dionperd** [comment]
Hello. Thanks for using tvb-multiscale and for you question!

tvb-multiscale undergoes heavy development, and, thus, it lacks a proper documentation from the moment. I am sorry about this.

I agree that the most likely problem is the version of NEST.

My own NEST models cannot compile for the moment for NEST 3.0, because they are made for an earlier version.
It is likely that you have the opposite problem.

I would suggest that you build you own docker image of tvb-multiscale using your desired version of NEST.

I have already started a branch for NEST v3.1:
https://github.com/the-virtual-brain/tvb-multiscale/tree/parallelNEST31

If you run the corresponding Dockerfile, you can create your own image (currently with NEST3.1, but you can modify the file to get a desired version):
https://github.com/the-virtual-brain/tvb-multiscale/blob/parallelNEST31/docker/Dockerfile

There might still be some problems when trying to run NEST 3.1, because I haven't really tested it.

Please refer to me and I can correct them asap.
Or, if you correct them yourself (it will be probably some NEST2 usages), please make a pull request with any changes.

Mind also that the toolbox API will have changed for this version of tvb-multiscale, as it is a transitory branch towards parallel cosimulation.
Please check the corresponding examples in scripts and notebooks.

We would love to know more about your modeling efforts with tvb-multiscale!

**Comment by Ninontwik** [comment]
Hello!

Thank you so much for the super quick and helpful support!
This worked! I build my own docker image of tvb-multiscale with NEST 3.1 and it works perfectly. Next I tried to install my own extension module of NEST and this worked perfectly like in their tutorial. 

So so far, so good. I might run into problems later because tvb-multiscale is not tested with NEST 3.1, but so far everything seems to work. But I should note that I am not at the point yet of fully integrating the spiking neuronal network model into the entire brain model. But I will let you know as soon as I run into some problems. 

If you are interested in the project, I am really excited to tell you something about it later! However, since it is quite new and still completely unpublished, I cannot tell you much now. But I am excited to work with tvb-multiscale, I think it will be a very valuable tool.

**Comment by dionperd** [comment]
Perfect! 

So, I am closing the issue and I will be waiting for whenever you would like to share more or need some more help with the tool!
